In [1]:
import pandas as pd

In [2]:
aq = pd.read_csv("Air_Quality.csv")

In [3]:
aq.head()

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
0,333939,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Winter 2014-15,12/01/2014,10.21,NaN
1,547354,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Annual Average 2017,01/01/2017,7.72,NaN
2,605650,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Winter 2017-18,12/01/2017,8.28,NaN
3,179503,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Winter 2010-11,12/01/2010,13.85,NaN
4,179643,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Annual Average 2009,12/01/2008,11.05,NaN

In [4]:
aq.Start_Date[0]

'12/01/2014'

In [5]:
from datetime import datetime

In [7]:
dt = [datetime.strptime(aq.Start_Date[i], '%m/%d/%Y') for i in range(len(aq))]

In [8]:
aq['Date']=dt

In [10]:
aq.head()

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message,Date
0,333939,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Winter 2014-15,12/01/2014,10.21,NaN,2014-12-01
1,547354,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Annual Average 2017,01/01/2017,7.72,NaN,2017-01-01
2,605650,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Winter 2017-18,12/01/2017,8.28,NaN,2017-12-01
3,179503,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Winter 2010-11,12/01/2010,13.85,NaN,2010-12-01
4,179643,365,Fine Particulate Matter (PM2.5),Mean,mcg per cubic meter,Borough,1,Bronx,Annual Average 2009,12/01/2008,11.05,NaN,2008-12-01

In [ ]:
aq = aq[['Data Value', 'Geo Place Name', 'Date']]